version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: co_work_db
    ports: [ "5432:5432" ]
#  mailer:
#    image: schickling/mailcatcher
#    ports: [ 1025, 1080 ]